import { UserRole } from '@nova/shared';

import { Entity } from '../../../common/domain/entity.base';
import { BusinessRuleViolation } from '../../../common/domain/domain.exceptions';

/** Persistent state of the `User` aggregate. */
export interface UserProps {
  id: string;
  email: string;
  displayName: string;
  passwordHash: string;
  role: UserRole;
  emailVerified: boolean;
  twoFactorEnabled: boolean;
  twoFactorSecret: string | null;
  recoveryCodes: string[];
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt: Date | null;
}

/**
 * Account aggregate root.
 *
 * Owns the authentication invariants: e-mail normalisation, two-factor
 * enrolment and recovery code consumption. It never talks to bcrypt, JWT or
 * the database — those are ports supplied by the application layer.
 */
export class User extends Entity<UserProps> {
  /**
   * Rehydrates an aggregate from storage.
   *
   * @param props - Persisted state.
   * @returns The reconstructed aggregate.
   */
  public static rehydrate(props: UserProps): User {
    return new User(props);
  }

  /**
   * Creates a brand new account.
   *
   * @param input - Identity, credentials and role of the new account.
   * @returns The created aggregate.
   * @throws {BusinessRuleViolation} When the display name is empty.
   */
  public static create(input: {
    id: string;
    email: string;
    displayName: string;
    passwordHash: string;
    role?: UserRole;
    now: Date;
  }): User {
    const displayName = input.displayName.trim();
    if (displayName.length < 2) {
      throw new BusinessRuleViolation('A megjelenítendő név legalább 2 karakter legyen.');
    }

    return new User({
      id: input.id,
      email: User.normaliseEmail(input.email),
      displayName,
      passwordHash: input.passwordHash,
      role: input.role ?? UserRole.MEMBER,
      emailVerified: false,
      twoFactorEnabled: false,
      twoFactorSecret: null,
      recoveryCodes: [],
      createdAt: input.now,
      updatedAt: input.now,
      lastLoginAt: null,
    });
  }

  /**
   * Normalises an e-mail address for storage and lookup.
   *
   * @param email - Raw address.
   * @returns Trimmed, lower-cased address.
   */
  public static normaliseEmail(email: string): string {
    return email.trim().toLowerCase();
  }

  /** Login address of the account. */
  public get email(): string {
    return this.props.email;
  }

  /** Password hash produced by the configured hasher. */
  public get passwordHash(): string {
    return this.props.passwordHash;
  }

  /** Authorisation role. */
  public get role(): UserRole {
    return this.props.role;
  }

  /** True when the account requires a TOTP code at login. */
  public get twoFactorEnabled(): boolean {
    return this.props.twoFactorEnabled;
  }

  /** Shared TOTP secret, or `null` when 2FA is not enrolled. */
  public get twoFactorSecret(): string | null {
    return this.props.twoFactorSecret;
  }

  /** Human readable account name. */
  public get displayName(): string {
    return this.props.displayName;
  }

  /**
   * Records a successful sign-in.
   *
   * @param now - Current instant supplied by the clock port.
   */
  public markLoggedIn(now: Date): void {
    this.props.lastLoginAt = now;
    this.props.updatedAt = now;
  }

  /**
   * Stores a pending TOTP secret before the user confirms enrolment.
   *
   * @param secret - Base32 secret generated by the TOTP port.
   */
  public stageTwoFactorSecret(secret: string): void {
    this.props.twoFactorSecret = secret;
  }

  /**
   * Completes two-factor enrolment.
   *
   * @param recoveryCodes - One-time recovery codes shown to the user once.
   * @throws {BusinessRuleViolation} When no secret was staged first.
   */
  public enableTwoFactor(recoveryCodes: string[]): void {
    if (!this.props.twoFactorSecret) {
      throw new BusinessRuleViolation('Előbb generálni kell egy 2FA titkot.');
    }
    this.props.twoFactorEnabled = true;
    this.props.recoveryCodes = recoveryCodes;
  }

  /** Removes two-factor authentication from the account. */
  public disableTwoFactor(): void {
    this.props.twoFactorEnabled = false;
    this.props.twoFactorSecret = null;
    this.props.recoveryCodes = [];
  }

  /**
   * Consumes a recovery code.
   *
   * @param code - Code entered by the user.
   * @returns True when the code was valid; each code works only once.
   */
  public consumeRecoveryCode(code: string): boolean {
    const index = this.props.recoveryCodes.indexOf(code.trim().toUpperCase());
    if (index === -1) {
      return false;
    }
    this.props.recoveryCodes.splice(index, 1);
    return true;
  }

  /**
   * Replaces the stored password hash.
   *
   * @param passwordHash - Newly derived hash.
   * @param now - Current instant.
   */
  public changePassword(passwordHash: string, now: Date): void {
    this.props.passwordHash = passwordHash;
    this.props.updatedAt = now;
  }

  /** Marks the e-mail address as verified. */
  public verifyEmail(): void {
    this.props.emailVerified = true;
  }

  /**
   * Promotes or demotes the account.
   *
   * @param role - Target role.
   */
  public changeRole(role: UserRole): void {
    this.props.role = role;
  }
}
